# fish completion for box-rpg
complete -c box-rpg -f
complete -c box-rpg -n '__fish_use_subcommand' -a cleanup -d 'Interactively remove launcher-managed data'
complete -c box-rpg -n '__fish_use_subcommand' -a inspect -d 'Inspect a supported game'
complete -c box-rpg -n '__fish_use_subcommand' -a runtime -d 'Manage game runtimes'
complete -c box-rpg -n '__fish_use_subcommand' -a launch -d 'Launch a supported game'
complete -c box-rpg -n '__fish_use_subcommand' -a config -d 'Show or set configuration'
complete -c box-rpg -n '__fish_use_subcommand' -a diagnose -d 'Check launcher setup'
complete -c box-rpg -n '__fish_seen_subcommand_from runtime; and not __fish_seen_subcommand_from list available install remove easyrpg' -a 'list available install remove easyrpg'
complete -c box-rpg -n '__fish_seen_subcommand_from easyrpg' -a 'list available install remove'
complete -c box-rpg -n '__fish_seen_subcommand_from easyrpg; and __fish_seen_subcommand_from available' -l page -d 'Select an EasyRPG Player version page'
complete -c box-rpg -n '__fish_seen_subcommand_from easyrpg; and __fish_seen_subcommand_from available' -l interactive -d 'Select and install an EasyRPG Player version'
complete -c box-rpg -n '__fish_seen_subcommand_from runtime; and not __fish_seen_subcommand_from easyrpg; and __fish_seen_subcommand_from available' -l page -d 'Select a five-version page'
complete -c box-rpg -n '__fish_seen_subcommand_from runtime; and not __fish_seen_subcommand_from easyrpg; and __fish_seen_subcommand_from available' -l interactive -d 'Select and install a version'
complete -c box-rpg -n '__fish_seen_subcommand_from runtime; and not __fish_seen_subcommand_from easyrpg' -l architecture -d 'Use an NW.js architecture'
complete -c box-rpg -n '__fish_seen_subcommand_from runtime; and not __fish_seen_subcommand_from easyrpg' -l sdk -d 'Use an NW.js SDK build'
complete -c box-rpg -n '__fish_seen_subcommand_from config' -a 'show set'
complete -c box-rpg -n '__fish_seen_subcommand_from launch' -l runtime -d 'Use an NW.js version'
complete -c box-rpg -n '__fish_seen_subcommand_from launch' -l sdk -d 'Use an NW.js SDK build'
complete -c box-rpg -n '__fish_seen_subcommand_from launch' -l game-cwd -d 'Use the game root as the NW.js working directory'
complete -c box-rpg -n '__fish_seen_subcommand_from launch' -l copy-root-file -d 'Copy a direct game-root file into the isolated session' -r
complete -c box-rpg -n '__fish_seen_subcommand_from diagnose' -l runtime -d 'Use an NW.js version'
complete -c box-rpg -n '__fish_seen_subcommand_from diagnose' -l sdk -d 'Use an NW.js SDK build'
