# pyright: reportPrivateUsage=false
"""Tests for the Python-pure AppImage builder (Fase 1 + Fase 2 + Fase 3)."""

import hashlib
import io
import os
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, cast

import install
import pytest

# The builder lives in the monorepo tools/ directory, which shares its
# package name with this test package (box-rpg/tests/tools). Prefer the
# real tools/ directory so `import build_appimage` never resolves here.
sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "tools"))

import appimage_tag
import build_appimage

# The tag is computed dynamically from git history: main() embeds whatever
# compute_version() returns at build time, so a hardcoded tag rots as soon
# as the month count moves.
TAG = build_appimage.compute_version(build_appimage.REPO_ROOT)


def _ok_run(args: list[str], cwd: Path | None = None) -> int:
    return 0


def _which_opt(name: str) -> str | None:
    return "/opt/python3"


def _which_old(name: str) -> str | None:
    return "/opt/old-python3"


def _which_none(name: str) -> str | None:
    return None


def _fixed_tag(*args: object) -> str:
    return TAG


def _tiny_body(*args: object, **kwargs: object) -> Any:
    return io.BytesIO(b"tiny")


def _empty_git_in(directory: Path, args: list[str]) -> str:
    return ""


def test_reader_contract_constants_match() -> None:
    """The builder and the fallback reader must share one contract."""
    assert build_appimage.APPIMAGE_TAG_ENV_VAR == appimage_tag.APPIMAGE_TAG_ENV_VAR
    assert build_appimage.APPIMAGE_TAG_FILENAME == appimage_tag.APPIMAGE_TAG_FILENAME
    assert build_appimage.APPIMAGE_TAG_ENV_VAR == "BOX_RPG_MAKER_APPIMAGE_TAG"
    assert build_appimage.APPIMAGE_TAG_FILENAME == "appimage_tag.txt"


def test_is_valid_tag_accepts_only_version_scheme() -> None:
    assert appimage_tag.is_valid_tag("26.9.43")
    assert not appimage_tag.is_valid_tag("v26.9.43")
    assert not appimage_tag.is_valid_tag("26.9")
    assert not appimage_tag.is_valid_tag("latest")
    assert not appimage_tag.is_valid_tag("26.9.43\n")


def test_repo_versions_match_dynamic_computation(monkeypatch: pytest.MonkeyPatch) -> None:
    """install.py reports the dynamic git version when nothing is installed."""
    from importlib import metadata

    def _missing(name: str) -> str:
        raise metadata.PackageNotFoundError(name)

    monkeypatch.setattr(metadata, "version", _missing)

    expected = build_appimage.compute_version(build_appimage.REPO_ROOT)
    assert install.repo_version() == expected
    assert install.gui_repo_version() == expected
    assert expected != "unknown"


def test_compute_version_counts_month_commits(monkeypatch: pytest.MonkeyPatch) -> None:
    """compute_version() counts month commits from git history."""

    def fake_run(cmd: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        assert cmd[0] == "git"
        assert any(arg.startswith("--since=2026-09-01") for arg in cmd)
        return subprocess.CompletedProcess(cmd, 0, stdout="aaa one\nbbb two\n", stderr="")

    import versioning

    monkeypatch.setattr(versioning.subprocess, "run", fake_run)

    assert (
        build_appimage.compute_version(build_appimage.REPO_ROOT, now=datetime(2026, 9, 17))
        == "26.9.2"
    )


def test_stage_appdir_layout(tmp_path: Path) -> None:
    appdir = tmp_path / "AppDir"

    build_appimage.stage_appdir(appdir, TAG)

    payload = appdir / "usr/share/box-rpg-maker"
    staged_gui = payload / "src" / "box_gui"
    assert (staged_gui / "app.py").is_file()
    assert (staged_gui / appimage_tag.APPIMAGE_TAG_FILENAME).read_text() == TAG + "\n"
    assert (staged_gui / "_version.py").read_text() == (
        f'# Generated by tools/versioning.py; do not edit by hand.\n__version__ = "{TAG}"\n'
    ), "staged payload pins the tag so runtime needs no git"
    assert list(staged_gui.glob("locale/**/box-rpg-maker.mo")), "locale catalogs ship along"
    assert not (payload / "src" / "box").exists(), "backend must never be staged"
    assert not list(payload.rglob("*.whl"))

    apprun = appdir / "AppRun"
    assert apprun.is_file() and os.access(apprun, os.X_OK)
    assert apprun.read_text().splitlines()[0] == "#!/usr/bin/python3"

    desktop = appdir / "io.gitlab.christvh.BoxRpgApp.desktop"
    content = desktop.read_text()
    assert "Exec=box-rpg-maker" in content
    assert "Icon=io.gitlab.christvh.BoxRpgApp" in content
    assert f"X-AppImage-Version={TAG}" in content
    assert (
        appdir / "usr/share/applications/io.gitlab.christvh.BoxRpgApp.desktop"
    ).read_text() == content

    icons = list((appdir / "usr/share/icons/hicolor/scalable/apps").glob("*.svg"))
    assert icons, "expected staged GUI icons"
    assert (appdir / "io.gitlab.christvh.BoxRpgApp.svg").is_file()
    assert (appdir / ".DirIcon").is_file()
    assert (payload / "res/io.gitlab.christvh.BoxRpgApp.desktop").is_file()


def test_stage_appdir_refuses_existing_or_malformed_tag(tmp_path: Path) -> None:
    appdir = tmp_path / "AppDir"
    appdir.mkdir()

    with pytest.raises(FileExistsError):
        build_appimage.stage_appdir(appdir, TAG)
    with pytest.raises(RuntimeError, match="malformed tag"):
        build_appimage.stage_appdir(tmp_path / "other", "latest")


def test_reject_backend_payload_fails_closed(tmp_path: Path) -> None:
    payload = tmp_path / "payload"
    (payload / "src" / "box").mkdir(parents=True)

    with pytest.raises(RuntimeError, match="backend"):
        build_appimage._reject_backend_payload(payload)


def test_apprun_source_runs_on_system_python_with_baked_tag() -> None:
    source = build_appimage.apprun_source(TAG)

    assert f'BUILD_TAG = "{TAG}"' in source
    assert appimage_tag.APPIMAGE_TAG_ENV_VAR in source
    assert "from box_gui.app import main" in source
    assert "import box.api" not in source
    assert "sys.version_info < (3, 14)" in source
    assert "staged payload missing" in source
    assert "staged frontend failed to import" in source
    assert "venv" not in source


def test_ensure_on_tag_creates_missing_tag(monkeypatch: pytest.MonkeyPatch) -> None:
    calls: list[list[str]] = []
    head = "abc123"

    def fake_git(args: list[str]) -> str:
        calls.append(args)
        if args[:2] == ["rev-parse", "--verify"]:
            raise RuntimeError("no such tag")
        if args == ["rev-parse", "HEAD"]:
            return head
        if args[0] == "tag":
            return ""
        if args[0] == "describe":
            return TAG
        if args[:2] == ["rev-list", "-n"]:
            return head
        raise AssertionError(f"unexpected git call: {args}")

    monkeypatch.setattr(build_appimage, "_run_git", fake_git)

    build_appimage.ensure_on_tag(TAG, create=True)

    assert ["tag", "-a", TAG, "-m", f"box-rpg-maker {TAG}"] in calls


def test_ensure_on_tag_refuses_a_moved_tag(monkeypatch: pytest.MonkeyPatch) -> None:
    calls: list[list[str]] = []

    def fake_git(args: list[str]) -> str:
        calls.append(args)
        if args[:2] == ["rev-parse", "--verify"]:
            return "tag-sha"
        if args[:2] == ["rev-list", "-n"]:
            return "other-commit"
        if args == ["rev-parse", "HEAD"]:
            return "head-commit"
        raise AssertionError(f"unexpected git call: {args}")

    monkeypatch.setattr(build_appimage, "_run_git", fake_git)

    with pytest.raises(RuntimeError, match="another commit"):
        build_appimage.ensure_on_tag(TAG, create=True)
    assert all(call[0] != "tag" for call in calls)


def test_ensure_on_tag_requires_exact_describe(monkeypatch: pytest.MonkeyPatch) -> None:
    def fake_git(args: list[str]) -> str:
        if args[:2] == ["rev-parse", "--verify"]:
            return "tag-sha"
        if args == ["rev-parse", "HEAD"] or args[:2] == ["rev-list", "-n"]:
            return "head-commit"
        if args[0] == "describe":
            return "26.9.42"
        raise AssertionError(f"unexpected git call: {args}")

    monkeypatch.setattr(build_appimage, "_run_git", fake_git)

    with pytest.raises(RuntimeError, match="not exactly at tag"):
        build_appimage.ensure_on_tag(TAG, create=True)


def _mock_build_prerequisites(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(build_appimage, "working_tree_clean", lambda: True)
    monkeypatch.setattr(build_appimage, "describe_head", lambda: TAG)


def test_main_check_passes_without_mutation(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    _mock_build_prerequisites(monkeypatch)
    monkeypatch.setattr(build_appimage.sys, "argv", ["build_appimage.py", "--check"])

    def forbidden(tag: str, *, create: bool) -> None:
        raise AssertionError("check mode must not create tags")

    monkeypatch.setattr(build_appimage, "ensure_on_tag", forbidden)

    assert build_appimage.main() == 0
    assert "Check passed" in capsys.readouterr().out


def test_main_print_tag_resolves_without_mutation(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """--print-tag reports the tag without touching git state or disk."""
    monkeypatch.setattr(build_appimage.sys, "argv", ["build_appimage.py", "--print-tag"])

    assert build_appimage.main() == 0
    assert capsys.readouterr().out.strip() == build_appimage.compute_version(
        build_appimage.REPO_ROOT
    )


def test_ensure_on_tag_without_creation_touches_nothing(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Local test builds embed without creating or verifying any tag."""

    def forbidden(args: list[str]) -> str:
        raise AssertionError(f"must not call git, got {args}")

    monkeypatch.setattr(build_appimage, "_run_git", forbidden)

    assert build_appimage.ensure_on_tag(TAG, create=False) is None


def test_main_refuses_dirty_tree(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.setattr(build_appimage, "working_tree_clean", lambda: False)
    monkeypatch.setattr(build_appimage.sys, "argv", ["build_appimage.py", "--tag", TAG])

    assert build_appimage.main() == 1
    assert "uncommitted changes" in capsys.readouterr().err


def test_get_appimage_tag_prefers_environment(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv(appimage_tag.APPIMAGE_TAG_ENV_VAR, "  26.9.43  ")

    assert appimage_tag.get_appimage_tag() == "26.9.43"


def test_get_appimage_tag_reads_staged_file(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.delenv(appimage_tag.APPIMAGE_TAG_ENV_VAR, raising=False)
    tag_file = tmp_path / appimage_tag.APPIMAGE_TAG_FILENAME
    tag_file.write_text(TAG + "\n")

    assert appimage_tag.get_appimage_tag(tmp_path) == TAG
    assert appimage_tag.get_appimage_tag(tag_file) == TAG


def test_get_appimage_tag_returns_none_when_absent(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.delenv(appimage_tag.APPIMAGE_TAG_ENV_VAR, raising=False)

    assert appimage_tag.get_appimage_tag() is None
    assert appimage_tag.get_appimage_tag(tmp_path) is None
    assert appimage_tag.read_tag_file(tmp_path / "missing.txt") is None


def test_ensure_appimagetool_rejects_unusable_binary(tmp_path: Path) -> None:
    with pytest.raises(RuntimeError, match="not executable"):
        build_appimage.ensure_appimagetool(
            tmp_path / "missing", build_appimage.APPIMAGETOOL_URL, tmp_path
        )
    plain = tmp_path / "plain"
    plain.write_bytes(b"not executable")
    with pytest.raises(RuntimeError, match="not executable"):
        build_appimage.ensure_appimagetool(plain, build_appimage.APPIMAGETOOL_URL, tmp_path)


def test_download_appimagetool_rejects_truncated_payload(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(build_appimage.urllib.request, "urlopen", _tiny_body)

    with pytest.raises(RuntimeError, match="truncated"):
        build_appimage.download_appimagetool("https://example.invalid/tool", tmp_path / "tool")


def test_extract_appimagetool_reports_missing_runner(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(build_appimage, "run", _ok_run)

    with pytest.raises(RuntimeError, match="missing its AppRun"):
        build_appimage.extract_appimagetool(tmp_path / "tool", tmp_path)


def test_build_artifact_runs_the_tool_and_marks_the_output(tmp_path: Path) -> None:
    runner = tmp_path / "runner"
    runner.write_text('#!/bin/sh\necho "artifact" > "$2"\n')
    runner.chmod(0o755)
    output = tmp_path / "dist" / "box-rpg-maker.appimage"

    result = build_appimage.build_artifact(runner, tmp_path / "AppDir", output)

    assert result == output
    assert output.is_file() and os.access(output, os.X_OK)


def test_build_artifact_fails_closed_on_tool_error(tmp_path: Path) -> None:
    runner = tmp_path / "runner"
    runner.write_text("#!/bin/sh\nexit 1\n")
    runner.chmod(0o755)

    with pytest.raises(RuntimeError, match="failed to build"):
        build_appimage.build_artifact(runner, tmp_path / "AppDir", tmp_path / "out.appimage")


def test_sha256_file_matches_hashlib(tmp_path: Path) -> None:
    """sha256_file() agrees with hashlib over binary content."""
    payload = tmp_path / "payload.bin"
    payload.write_bytes(b"hello appimage\n\x00\xff" * 5000)

    assert build_appimage.sha256_file(payload) == hashlib.sha256(payload.read_bytes()).hexdigest()


def test_sha256_file_fails_closed_on_missing_file(tmp_path: Path) -> None:
    """A missing input fails closed instead of returning a digest."""
    with pytest.raises(RuntimeError, match="cannot hash"):
        build_appimage.sha256_file(tmp_path / "missing.bin")


def test_build_artifact_writes_matching_checksum(tmp_path: Path) -> None:
    """build_artifact() writes <output>.sha256 with '<hex>  <basename>'."""
    runner = tmp_path / "runner"
    runner.write_text('#!/bin/sh\necho "artifact" > "$2"\n')
    runner.chmod(0o755)
    output = tmp_path / "dist" / "box-rpg-maker.appimage"

    result = build_appimage.build_artifact(runner, tmp_path / "AppDir", output)

    assert result == output
    checksum_path = output.with_name(output.name + ".sha256")
    expected = hashlib.sha256(output.read_bytes()).hexdigest()
    assert checksum_path.read_text(encoding="utf-8") == f"{expected}  {output.name}\n"
    assert build_appimage.sha256_file(output) == expected


def _load_apprun_namespace() -> dict[str, Any]:
    """Exec the generated AppRun in isolation for re-exec tests."""
    source = build_appimage.apprun_source(TAG)
    namespace: dict[str, Any] = {
        "__name__": "apprun_under_test",
        "__file__": "/fake/AppRun",
    }
    exec(source, namespace)
    return namespace


class _ExecCalled(Exception):
    """Sentinel standing in for the noreturn os.execve in tests."""


def test_apprun_reexec_picks_suitable_candidate(monkeypatch: pytest.MonkeyPatch) -> None:
    """The first suitable python is execed once, after earlier ones fail."""
    namespace = _load_apprun_namespace()
    monkeypatch.delenv("BOX_RPG_MAKER_PYTHON", raising=False)
    monkeypatch.delenv("BOX_RPG_MAKER_REEXECED", raising=False)
    monkeypatch.setattr(sys, "executable", "/usr/bin/python3.13-test")

    def fake_which(name: str) -> str | None:
        assert name == "python3"
        return "/opt/python3"

    monkeypatch.setattr(shutil, "which", fake_which)
    probed: list[str] = []

    def fake_run(args: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        probed.append(args[0])
        code = 0 if args[0] == "/usr/local/bin/python3" else 1
        return subprocess.CompletedProcess(args, code, "", "")

    monkeypatch.setattr(subprocess, "run", fake_run)
    exec_calls: list[tuple[str, list[str]]] = []

    def fake_execve(path: str, argv: list[str], env: dict[str, str]) -> None:
        exec_calls.append((path, list(argv)))
        raise _ExecCalled

    monkeypatch.setattr(os, "execve", fake_execve)
    monkeypatch.setattr(sys, "argv", ["AppRun", "--foo"])

    with pytest.raises(_ExecCalled):
        namespace["_reexec_with_suitable_python"]()

    assert probed == ["/opt/python3", "/usr/local/bin/python3"]
    assert exec_calls == [("/usr/local/bin/python3", ["/usr/local/bin/python3", "AppRun", "--foo"])]


def test_apprun_env_override_wins(monkeypatch: pytest.MonkeyPatch) -> None:
    """The env override is probed before PATH and the well-known paths."""
    namespace = _load_apprun_namespace()
    monkeypatch.setenv("BOX_RPG_MAKER_PYTHON", "/usr/local/bin/python3.14")
    monkeypatch.delenv("BOX_RPG_MAKER_REEXECED", raising=False)
    monkeypatch.setattr(sys, "executable", "/usr/bin/python3.13-test")

    def fake_which(name: str) -> str | None:
        assert name == "python3"
        return "/opt/other/python3"

    monkeypatch.setattr(shutil, "which", fake_which)
    probed: list[str] = []

    def fake_run(args: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        probed.append(args[0])
        return subprocess.CompletedProcess(args, 0, "", "")

    monkeypatch.setattr(subprocess, "run", fake_run)
    exec_calls: list[tuple[str, list[str]]] = []

    def fake_execve(path: str, argv: list[str], env: dict[str, str]) -> None:
        exec_calls.append((path, list(argv)))
        assert env.get("BOX_RPG_MAKER_REEXECED") == "1"
        raise _ExecCalled

    monkeypatch.setattr(os, "execve", fake_execve)
    monkeypatch.setattr(sys, "argv", ["AppRun"])

    with pytest.raises(_ExecCalled):
        namespace["_reexec_with_suitable_python"]()

    assert probed == ["/usr/local/bin/python3.14"]
    assert exec_calls == [
        (
            "/usr/local/bin/python3.14",
            ["/usr/local/bin/python3.14", "AppRun"],
        )
    ]


def test_apprun_exec_failure_falls_through_to_next(monkeypatch: pytest.MonkeyPatch) -> None:
    """An OSError at exec time moves on to the next suitable candidate."""
    namespace = _load_apprun_namespace()
    monkeypatch.delenv("BOX_RPG_MAKER_PYTHON", raising=False)
    monkeypatch.delenv("BOX_RPG_MAKER_REEXECED", raising=False)
    monkeypatch.setattr(sys, "executable", "/usr/bin/python3.13-test")
    monkeypatch.setattr(sys, "argv", ["AppRun"])
    monkeypatch.setattr(shutil, "which", _which_opt)

    def fake_run(args: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        assert kwargs.get("timeout") == 10
        assert kwargs.get("stdin") is subprocess.DEVNULL
        return subprocess.CompletedProcess(args, 0, "", "")

    monkeypatch.setattr(subprocess, "run", fake_run)
    exec_calls: list[str] = []

    def fake_execve(path: str, argv: list[str], env: dict[str, str]) -> None:
        exec_calls.append(path)
        if len(exec_calls) == 1:
            raise OSError("busy")
        raise _ExecCalled

    monkeypatch.setattr(os, "execve", fake_execve)

    with pytest.raises(_ExecCalled):
        namespace["_reexec_with_suitable_python"]()

    assert exec_calls == ["/opt/python3", "/usr/local/bin/python3"]


def test_apprun_reexec_marker_stops_second_pass(monkeypatch: pytest.MonkeyPatch) -> None:
    """A preset marker returns quietly without probing or execing anything."""
    namespace = _load_apprun_namespace()
    monkeypatch.setenv("BOX_RPG_MAKER_REEXECED", "1")
    monkeypatch.setattr(sys, "executable", "/usr/bin/python3.13-test")

    def forbidden_which(name: str) -> str | None:
        raise AssertionError("must not look up interpreters")

    def forbidden_run(args: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        raise AssertionError("must not probe interpreters")

    def forbidden_execve(path: str, argv: list[str], env: dict[str, str]) -> None:
        raise AssertionError("must not exec")

    monkeypatch.setattr(shutil, "which", forbidden_which)
    monkeypatch.setattr(subprocess, "run", forbidden_run)
    monkeypatch.setattr(os, "execve", forbidden_execve)

    namespace["_reexec_with_suitable_python"]()


def test_apprun_relative_override_and_current_are_skipped(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A relative override is ignored and the running interpreter is skipped."""
    namespace = _load_apprun_namespace()
    monkeypatch.setenv("BOX_RPG_MAKER_PYTHON", "python3.14")
    monkeypatch.delenv("BOX_RPG_MAKER_REEXECED", raising=False)
    monkeypatch.setattr(sys, "executable", "/opt/python3")
    monkeypatch.setattr(sys, "argv", ["AppRun"])
    monkeypatch.setattr(shutil, "which", _which_opt)
    probed: list[str] = []

    def fake_run(args: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        probed.append(args[0])
        return subprocess.CompletedProcess(args, 0, "", "")

    monkeypatch.setattr(subprocess, "run", fake_run)

    def fake_execve(path: str, argv: list[str], env: dict[str, str]) -> None:
        raise _ExecCalled

    monkeypatch.setattr(os, "execve", fake_execve)

    with pytest.raises(_ExecCalled):
        namespace["_reexec_with_suitable_python"]()
    assert probed == ["/usr/local/bin/python3"]


def test_apprun_main_reexecs_before_failing(monkeypatch: pytest.MonkeyPatch) -> None:
    """On an old interpreter, main() re-execs instead of failing directly."""
    namespace = _load_apprun_namespace()
    monkeypatch.delenv("BOX_RPG_MAKER_PYTHON", raising=False)
    monkeypatch.delenv("BOX_RPG_MAKER_REEXECED", raising=False)
    monkeypatch.setattr(sys, "executable", "/usr/bin/python3.13-test")

    def fake_which(name: str) -> str | None:
        assert name == "python3"
        return "/opt/python3"

    monkeypatch.setattr(shutil, "which", fake_which)

    def fake_run(args: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(args, 0, "", "")

    monkeypatch.setattr(subprocess, "run", fake_run)

    def fake_execve(path: str, argv: list[str], env: dict[str, str]) -> None:
        raise _ExecCalled

    monkeypatch.setattr(os, "execve", fake_execve)
    monkeypatch.setattr(sys, "version_info", (3, 13))
    monkeypatch.setattr(sys, "argv", ["AppRun"])

    with pytest.raises(_ExecCalled):
        namespace["main"]()


def test_apprun_nogui_reports_bindings_hint(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """Runners without GTK bindings get the PyGObject hint, not the version one."""
    namespace = _load_apprun_namespace()
    monkeypatch.delenv("BOX_RPG_MAKER_PYTHON", raising=False)
    monkeypatch.delenv("BOX_RPG_MAKER_REEXECED", raising=False)
    monkeypatch.setattr(sys, "executable", "/usr/bin/python3.13-test")

    def fake_which(name: str) -> str | None:
        assert name == "python3"
        return None

    monkeypatch.setattr(shutil, "which", fake_which)

    def fake_run(args: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(args, 1, "", "")

    monkeypatch.setattr(subprocess, "run", fake_run)
    exec_calls: list[tuple[str, list[str]]] = []

    def fake_execve(path: str, argv: list[str], env: dict[str, str]) -> None:
        exec_calls.append((path, list(argv)))

    monkeypatch.setattr(os, "execve", fake_execve)
    monkeypatch.setattr(sys, "version_info", (3, 13))
    monkeypatch.setattr(sys, "argv", ["AppRun"])

    assert namespace["main"]() == 1
    err = capsys.readouterr().err
    assert "No Python 3.14 with GTK bindings found" in err
    assert "BOX_RPG_MAKER_PYTHON" in err
    assert exec_calls == []


def test_apprun_old_gui_keeps_version_message(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """Bindings on old interpreters only keep the plain version message."""
    namespace = _load_apprun_namespace()
    monkeypatch.delenv("BOX_RPG_MAKER_PYTHON", raising=False)
    monkeypatch.delenv("BOX_RPG_MAKER_REEXECED", raising=False)
    monkeypatch.setattr(sys, "executable", "/usr/bin/python3.13-test")
    monkeypatch.setattr(shutil, "which", _which_none)

    def fake_run(args: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(args, 2, "", "")

    monkeypatch.setattr(subprocess, "run", fake_run)

    def forbidden_execve(path: str, argv: list[str], env: dict[str, str]) -> None:
        raise AssertionError("must not exec without an ok candidate")

    monkeypatch.setattr(os, "execve", forbidden_execve)
    monkeypatch.setattr(sys, "version_info", (3, 13))
    monkeypatch.setattr(sys, "argv", ["AppRun"])

    assert namespace["main"]() == 1
    assert "Python 3.14+ required" in capsys.readouterr().err


def test_apprun_mixed_old_and_nogui_prefers_bindings_hint(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """A 3.14 without bindings beats an old interpreter with them in the hint."""
    namespace = _load_apprun_namespace()
    monkeypatch.delenv("BOX_RPG_MAKER_PYTHON", raising=False)
    monkeypatch.delenv("BOX_RPG_MAKER_REEXECED", raising=False)
    monkeypatch.setattr(sys, "executable", "/usr/bin/python3.13-test")
    monkeypatch.setattr(shutil, "which", _which_old)

    def fake_run(args: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        code = 2 if args[0] == "/opt/old-python3" else 1
        return subprocess.CompletedProcess(args, code, "", "")

    monkeypatch.setattr(subprocess, "run", fake_run)

    def forbidden_execve(path: str, argv: list[str], env: dict[str, str]) -> None:
        raise AssertionError("must not exec without an ok candidate")

    monkeypatch.setattr(os, "execve", forbidden_execve)
    monkeypatch.setattr(sys, "version_info", (3, 13))
    monkeypatch.setattr(sys, "argv", ["AppRun"])

    assert namespace["main"]() == 1
    assert "No Python 3.14 with GTK bindings found" in capsys.readouterr().err


def test_apprun_probe_classifies_candidates(monkeypatch: pytest.MonkeyPatch) -> None:
    """Exit codes and failures map to ok, old, nogui, and unusable."""
    namespace = _load_apprun_namespace()
    probe = namespace["_probe_python"]

    def run_with(code: int | None) -> str:
        def fake_run(args: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
            if code is None:
                raise OSError("gone")
            return subprocess.CompletedProcess(args, code, "", "")

        monkeypatch.setattr(subprocess, "run", fake_run)
        return probe("/opt/python3")

    assert run_with(0) == "ok"
    assert run_with(2) == "old"
    assert run_with(1) == "nogui"
    assert run_with(None) == "unusable"

    def timeout_run(args: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        raise subprocess.TimeoutExpired(args, 10)

    monkeypatch.setattr(subprocess, "run", timeout_run)
    assert probe("/opt/python3") == "unusable"


def _stable_test_git(args: list[str]) -> str:
    """Read-only git answers for test-build fingerprint tests."""
    if args == ["rev-parse", "HEAD"]:
        return "abc123deadbeef"
    if args == ["status", "--porcelain"]:
        return " M dirty.txt"
    if args == ["tag", "-l"]:
        return "26.9.1\n26.9.2"
    if args[0] == "log":
        return "aaa one\n"
    raise AssertionError(f"unexpected git call: {args}")


def _mock_snapshot_fs(monkeypatch: pytest.MonkeyPatch) -> None:
    """Replace snapshot copy and snapshot git writes with headless fakes."""

    def fake_snapshot(dest: Path) -> Path:
        dest.mkdir(parents=True)
        (dest / "marker.txt").write_text("snapshot")
        return dest

    def fake_git_in(directory: Path, args: list[str]) -> str:
        assert directory != build_appimage.REPO_ROOT
        assert args[0] in ("add", "-c", "commit")
        return ""

    monkeypatch.setattr(build_appimage, "snapshot_tree", fake_snapshot)
    monkeypatch.setattr(build_appimage, "_run_git_in", fake_git_in)


def test_snapshot_tree_excludes_build_artifacts(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Caches, dist, tools/target, and AppImages never enter the snapshot."""
    fake_root = tmp_path / "fake-root"
    (fake_root / "keep").mkdir(parents=True)
    (fake_root / "keep" / "file.txt").write_text("keep")
    (fake_root / ".venv" / "lib").mkdir(parents=True)
    (fake_root / ".venv" / "lib" / "x.py").write_text("x")
    (fake_root / ".venv-gui" / "lib").mkdir(parents=True)
    (fake_root / ".venv-gui" / "lib" / "x.py").write_text("x")
    (fake_root / "pkg" / "__pycache__").mkdir(parents=True)
    (fake_root / "pkg" / "__pycache__" / "c.pyc").write_bytes(b"x")
    (fake_root / ".pytest_cache" / "v").mkdir(parents=True)
    (fake_root / ".pytest_cache" / "v" / "cache").write_text("x")
    (fake_root / ".ruff_cache").mkdir()
    (fake_root / ".ruff_cache" / "r").write_text("x")
    (fake_root / "dist").mkdir()
    (fake_root / "dist" / "old.appimage").write_text("x")
    (fake_root / "tools" / "target").mkdir(parents=True)
    (fake_root / "tools" / "target" / "prev.appimage").write_text("x")
    (fake_root / "tools" / "keep.py").write_text("x")
    (fake_root / "sub" / "nested.appimage").parent.mkdir(parents=True)
    (fake_root / "sub" / "nested.appimage").write_text("x")
    (fake_root / "sub" / "ok.txt").write_text("ok")
    monkeypatch.setattr(build_appimage, "REPO_ROOT", fake_root)

    dest = tmp_path / "snap"
    build_appimage.snapshot_tree(dest)

    assert (dest / "keep" / "file.txt").is_file()
    assert (dest / "tools" / "keep.py").is_file()
    assert (dest / "sub" / "ok.txt").is_file()
    assert not (dest / ".venv").exists()
    assert not (dest / ".venv-gui").exists()
    assert not (dest / "pkg" / "__pycache__").exists()
    assert not (dest / ".pytest_cache").exists()
    assert not (dest / ".ruff_cache").exists()
    assert not (dest / "dist").exists()
    assert not (dest / "tools" / "target").exists()
    assert not list(dest.rglob("*.appimage"))


def test_test_build_forwards_explicit_tag(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """An explicit tag reaches the inner snapshot build verbatim."""
    monkeypatch.setattr(build_appimage, "_run_git", _stable_test_git)
    _mock_snapshot_fs(monkeypatch)
    captured: dict[str, object] = {}

    def fake_run(args: list[str], cwd: Path | None = None) -> int:
        captured["args"] = list(args)
        captured["cwd"] = cwd
        return 0

    monkeypatch.setattr(build_appimage, "run", fake_run)
    output = tmp_path / "out" / "box-rpg-maker-test.appimage"

    result = build_appimage.test_build(
        TAG,
        output,
        appdir_only=False,
        force=False,
        appimagetool=None,
        appimagetool_url=build_appimage.APPIMAGETOOL_URL,
        appimagetool_mode="extract",
    )

    assert result == output.resolve()
    command = captured["args"]
    assert isinstance(command, list)
    argv = cast(list[str], command)
    assert command[:3] == [sys.executable, "-m", "tools.build_appimage"]
    assert "--yes" in command
    assert "--no-create-tag" in command
    assert "--tag" in command
    assert argv[argv.index("--tag") + 1] == TAG
    assert "--output" in command
    assert captured["cwd"] is not None
    assert captured["cwd"] != build_appimage.REPO_ROOT


def test_test_build_resolves_tag_when_empty(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """An empty tag is resolved in the real repo before snapshotting."""
    monkeypatch.setattr(build_appimage, "_run_git", _stable_test_git)
    monkeypatch.setattr(build_appimage, "compute_version", _fixed_tag)
    _mock_snapshot_fs(monkeypatch)
    captured: dict[str, object] = {}

    def fake_run(args: list[str], cwd: Path | None = None) -> int:
        captured["args"] = list(args)
        return 0

    monkeypatch.setattr(build_appimage, "run", fake_run)
    output = tmp_path / "out.appimage"

    build_appimage.test_build(
        None,
        output,
        appdir_only=False,
        force=False,
        appimagetool=None,
        appimagetool_url=build_appimage.APPIMAGETOOL_URL,
        appimagetool_mode="extract",
    )

    command = captured["args"]
    assert isinstance(command, list)
    argv = cast(list[str], command)
    assert argv[argv.index("--tag") + 1] == TAG


def test_test_build_refuses_in_repo_output(monkeypatch: pytest.MonkeyPatch) -> None:
    """Explicit in-repo outputs other than the test default are refused."""
    monkeypatch.setattr(build_appimage, "_run_git", _stable_test_git)

    def forbidden_snapshot(dest: Path) -> Path:
        raise AssertionError("refused output must not snapshot")

    monkeypatch.setattr(build_appimage, "snapshot_tree", forbidden_snapshot)
    bad = build_appimage.REPO_ROOT / "dist" / "custom.appimage"
    with pytest.raises(RuntimeError, match="in-repo"):
        build_appimage.test_build(
            TAG,
            bad,
            appdir_only=False,
            force=False,
            appimagetool=None,
            appimagetool_url=build_appimage.APPIMAGETOOL_URL,
            appimagetool_mode="extract",
        )
    assert build_appimage._resolve_test_output(None) == build_appimage.TEST_DEFAULT_OUTPUT
    allowed = build_appimage._resolve_test_output(build_appimage.TEST_DEFAULT_OUTPUT)
    assert allowed == build_appimage.TEST_DEFAULT_OUTPUT.resolve()


def test_test_build_verifies_fingerprint(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """A changed HEAD, status, or tag count after the build fails closed."""
    calls = {"count": 0}

    def changing_git(args: list[str]) -> str:
        calls["count"] += 1
        if args == ["rev-parse", "HEAD"]:
            return "after-head" if calls["count"] > 3 else "before-head"
        return _stable_test_git(args)

    monkeypatch.setattr(build_appimage, "_run_git", changing_git)
    _mock_snapshot_fs(monkeypatch)
    monkeypatch.setattr(build_appimage, "run", _ok_run)

    with pytest.raises(RuntimeError, match="changed during"):
        build_appimage.test_build(
            TAG,
            tmp_path / "out.appimage",
            appdir_only=False,
            force=False,
            appimagetool=None,
            appimagetool_url=build_appimage.APPIMAGETOOL_URL,
            appimagetool_mode="extract",
        )


def test_test_build_creates_no_tags(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """The real repo only sees reads; writes stay inside the snapshot."""
    seen: list[list[str]] = []
    snapshot_dirs: list[Path] = []

    def recording_git(args: list[str]) -> str:
        seen.append(list(args))
        return _stable_test_git(args)

    def recording_git_in(directory: Path, args: list[str]) -> str:
        snapshot_dirs.append(directory)
        assert directory != build_appimage.REPO_ROOT
        return ""

    monkeypatch.setattr(build_appimage, "_run_git", recording_git)
    monkeypatch.setattr(build_appimage, "_run_git_in", recording_git_in)

    def fake_snapshot(dest: Path) -> Path:
        dest.mkdir(parents=True)
        return dest

    monkeypatch.setattr(build_appimage, "snapshot_tree", fake_snapshot)
    monkeypatch.setattr(build_appimage, "run", _ok_run)

    build_appimage.test_build(
        TAG,
        tmp_path / "out.appimage",
        appdir_only=False,
        force=False,
        appimagetool=None,
        appimagetool_url=build_appimage.APPIMAGETOOL_URL,
        appimagetool_mode="extract",
    )

    assert seen, "expected read-only git probes"
    for args in seen:
        assert args[0] in ("rev-parse", "status", "tag", "log")
        assert args[:2] != ["tag", "-a"]
    assert snapshot_dirs, "expected snapshot-local add and commit"


def test_test_build_cleans_tempdir_on_failure(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A failed inner build still removes the TemporaryDirectory snapshot."""
    monkeypatch.setattr(build_appimage, "_run_git", _stable_test_git)
    monkeypatch.setattr(build_appimage, "_run_git_in", _empty_git_in)
    captured: dict[str, object] = {}

    def fake_run(args: list[str], cwd: Path | None = None) -> int:
        captured["cwd"] = cwd
        return 1

    monkeypatch.setattr(build_appimage, "run", fake_run)

    with pytest.raises(RuntimeError, match="failed in snapshot"):
        build_appimage.test_build(
            TAG,
            tmp_path / "out.appimage",
            appdir_only=False,
            force=False,
            appimagetool=None,
            appimagetool_url=build_appimage.APPIMAGETOOL_URL,
            appimagetool_mode="extract",
        )

    snapshot = captured["cwd"]
    assert isinstance(snapshot, Path)
    assert not snapshot.exists()
    assert not snapshot.parent.exists()


def test_test_build_passes_appdir_only_flags(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """AppDir-only, force, and tool selection reach the inner command."""
    monkeypatch.setattr(build_appimage, "_run_git", _stable_test_git)
    _mock_snapshot_fs(monkeypatch)
    captured: dict[str, object] = {}

    def fake_run(args: list[str], cwd: Path | None = None) -> int:
        captured["args"] = list(args)
        return 0

    monkeypatch.setattr(build_appimage, "run", fake_run)
    tool = tmp_path / "tool"
    tool.write_text("x")
    output = tmp_path / "AppDir"

    build_appimage.test_build(
        TAG,
        output,
        appdir_only=True,
        force=True,
        appimagetool=tool,
        appimagetool_url="https://example.invalid/tool",
        appimagetool_mode="run",
    )

    command = captured["args"]
    assert isinstance(command, list)
    argv = cast(list[str], command)
    assert "--appdir-only" in command
    assert "--force" in command
    assert "--appimagetool" in command
    assert argv[argv.index("--appimagetool") + 1] == str(tool)
    assert "--appimagetool-url" in command
    assert argv[argv.index("--appimagetool-url") + 1] == "https://example.invalid/tool"
    assert "--appimagetool-mode" in command
    assert argv[argv.index("--appimagetool-mode") + 1] == "run"
    assert "--no-create-tag" in command


def test_test_build_refuses_linked_worktree(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A .git file (linked worktree) fails before any snapshot exists."""
    fake_root = tmp_path / "linked"
    fake_root.mkdir()
    (fake_root / ".git").write_text("gitdir: /elsewhere")
    monkeypatch.setattr(build_appimage, "REPO_ROOT", fake_root)

    def forbidden_git(args: list[str]) -> str:
        raise AssertionError("refused worktree must not run git")

    monkeypatch.setattr(build_appimage, "_run_git", forbidden_git)

    with pytest.raises(RuntimeError, match="linked worktree"):
        build_appimage.test_build(
            TAG,
            tmp_path / "out.appimage",
            appdir_only=False,
            force=False,
            appimagetool=None,
            appimagetool_url=build_appimage.APPIMAGETOOL_URL,
            appimagetool_mode="extract",
        )


def test_test_build_resolves_relative_appimagetool(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A relative tool path is anchored at the caller cwd, not the snapshot."""
    monkeypatch.setattr(build_appimage, "_run_git", _stable_test_git)
    _mock_snapshot_fs(monkeypatch)
    monkeypatch.chdir(tmp_path)
    captured: dict[str, object] = {}

    def fake_run(args: list[str], cwd: Path | None = None) -> int:
        captured["args"] = list(args)
        return 0

    monkeypatch.setattr(build_appimage, "run", fake_run)

    build_appimage.test_build(
        TAG,
        tmp_path / "out.appimage",
        appdir_only=False,
        force=False,
        appimagetool=Path("rel-tool"),
        appimagetool_url=build_appimage.APPIMAGETOOL_URL,
        appimagetool_mode="extract",
    )

    command = captured["args"]
    assert isinstance(command, list)
    argv = cast(list[str], command)
    assert argv[argv.index("--appimagetool") + 1] == str(tmp_path / "rel-tool")


def test_test_build_detects_tag_rename_with_same_count(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A tag rename (same count, different list) fails the fingerprint."""
    calls = {"count": 0}

    def renaming_git(args: list[str]) -> str:
        calls["count"] += 1
        if args == ["tag", "-l"]:
            return "26.9.1\n26.9.2" if calls["count"] <= 3 else "26.9.1\n26.9.3"
        return _stable_test_git(args)

    monkeypatch.setattr(build_appimage, "_run_git", renaming_git)
    _mock_snapshot_fs(monkeypatch)
    monkeypatch.setattr(build_appimage, "run", _ok_run)

    with pytest.raises(RuntimeError, match="tags differ"):
        build_appimage.test_build(
            TAG,
            tmp_path / "out.appimage",
            appdir_only=False,
            force=False,
            appimagetool=None,
            appimagetool_url=build_appimage.APPIMAGETOOL_URL,
            appimagetool_mode="extract",
        )


def test_test_build_refuses_output_inside_snapshot(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """An output inside the snapshot workspace is refused before snapshotting."""
    monkeypatch.setattr(build_appimage, "_run_git", _stable_test_git)
    workspace = tmp_path / "ws"

    class _FixedTmp:
        def __enter__(self) -> str:
            workspace.mkdir(parents=True, exist_ok=True)
            return str(workspace)

        def __exit__(self, *exc: object) -> bool:
            return False

    def _fixed_tmpdir(*args: object, **kwargs: object) -> Any:
        return _FixedTmp()

    monkeypatch.setattr(build_appimage.tempfile, "TemporaryDirectory", _fixed_tmpdir)

    def forbidden_snapshot(dest: Path) -> Path:
        raise AssertionError("refused output must not snapshot")

    monkeypatch.setattr(build_appimage, "snapshot_tree", forbidden_snapshot)

    with pytest.raises(RuntimeError, match="snapshot workspace"):
        build_appimage.test_build(
            TAG,
            workspace / "tree" / "out.appimage",
            appdir_only=False,
            force=False,
            appimagetool=None,
            appimagetool_url=build_appimage.APPIMAGETOOL_URL,
            appimagetool_mode="extract",
        )


def test_test_build_tmp_commit_carries_identity(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The snapshot commit pins an author so identity-less hosts still work."""
    monkeypatch.setattr(build_appimage, "_run_git", _stable_test_git)
    _mock_snapshot_fs(monkeypatch)
    monkeypatch.setattr(build_appimage, "run", _ok_run)
    commands: list[list[str]] = []
    real_git_in = build_appimage._run_git_in

    def recording_git_in(directory: Path, args: list[str]) -> str:
        commands.append(list(args))
        return real_git_in(directory, args)

    monkeypatch.setattr(build_appimage, "_run_git_in", recording_git_in)

    build_appimage.test_build(
        TAG,
        tmp_path / "out.appimage",
        appdir_only=False,
        force=False,
        appimagetool=None,
        appimagetool_url=build_appimage.APPIMAGETOOL_URL,
        appimagetool_mode="extract",
    )

    commits = [args for args in commands if "commit" in args]
    assert len(commits) == 1
    assert "-c" in commits[0]
    assert "user.name=box-rpg-maker-test" in commits[0]


def test_snapshot_tree_preserves_symlinks(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Links stay links instead of materializing their targets in the snapshot."""
    fake_root = tmp_path / "fake-root"
    (fake_root / "real").mkdir(parents=True)
    (fake_root / "real" / "file.txt").write_text("data")
    (fake_root / "link").symlink_to(fake_root / "real", target_is_directory=True)
    monkeypatch.setattr(build_appimage, "REPO_ROOT", fake_root)

    dest = tmp_path / "snap"
    build_appimage.snapshot_tree(dest)

    assert (dest / "link").is_symlink()
    assert (dest / "link" / "file.txt").read_text() == "data"


def test_main_rejects_test_build_with_check(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """--test-build combined with --check fails instead of building."""
    monkeypatch.setattr(sys, "argv", ["build_appimage.py", "--test-build", "--check"])

    assert build_appimage.main() == 1
    assert "mutually exclusive" in capsys.readouterr().err
