"""Dynamic version computation for the box-project monorepo.

The version follows the ``year.month.commit-count`` scheme (e.g. ``26.9.4``):
two-digit year, month without leading zero, and the number of commits
reachable from HEAD since the first day of that month at 00:00:00.

The version is never stored in source files. It is computed from git
history at build/CI time and pinned into the artifact.

A release tag (``year.month.count``) pointing exactly at HEAD takes
precedence over the commit count, so checkouts of a release tag report
the released version even when the clone is shallow. A shallow clone
with no such tag fails closed instead of guessing a count.
"""

from __future__ import annotations

import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

_TAG_PATTERN = re.compile(r"^\d+\.\d+\.\d+$")


def _find_repo_root(start: str | Path) -> Path:
    """Walk up from ``start`` until a directory containing ``.git`` is found."""
    current = Path(start).resolve()
    if current.is_file():
        current = current.parent
    for candidate in (current, *current.parents):
        if (candidate / ".git").exists():
            return candidate
    raise RuntimeError(
        f"no .git directory found at or above {current}; "
        "pass the monorepo root (or a path inside it) as repo_root"
    )


def _exact_release_tag(root: Path) -> str | None:
    """Return the highest ``year.month.count`` tag pointing at HEAD, if any.

    Tags not matching the version scheme are ignored. Any failure of this
    auxiliary probe (no git, old git, mocked subprocess, ...) means
    "no usable tag", never an error: the caller falls back to counting.
    """
    try:
        proc = subprocess.run(
            ["git", "tag", "--points-at", "HEAD"],
            cwd=root,
            capture_output=True,
            text=True,
            check=False,
        )
    except Exception:
        return None
    if proc.returncode != 0:
        return None
    candidates = [tag for tag in (line.strip() for line in proc.stdout.splitlines()) if tag]
    matching = [tag for tag in candidates if _TAG_PATTERN.fullmatch(tag)]
    if not matching:
        return None
    return max(matching, key=lambda tag: tuple(int(part) for part in tag.split(".")))


def _is_shallow_repository(root: Path) -> bool:
    """Return True only on an explicit shallow marker from git.

    Any failure of this auxiliary probe means "unknown", never shallow, so
    the happy path keeps working when the probe cannot run.
    """
    try:
        proc = subprocess.run(
            ["git", "rev-parse", "--is-shallow-repository"],
            cwd=root,
            capture_output=True,
            text=True,
            check=False,
        )
    except Exception:
        return False
    return proc.returncode == 0 and proc.stdout.strip() == "true"


def compute_version(repo_root: str | Path = ".", now: datetime | None = None) -> str:
    """Compute the ``year.month.commit-count`` version from git history.

    ``repo_root`` may point anywhere inside the monorepo (the monorepo
    root itself, ``box-rpg/``, ``box-gui/``, ...); it is resolved upward
    to the directory containing ``.git`` so every package gets the same
    number. ``now`` overrides the current time (used in tests).

    A release tag pointing exactly at HEAD wins over the commit count, so
    tag checkouts (even shallow ones) report the released version. A
    shallow clone without such a tag fails closed with RuntimeError
    because the monthly commit count would be unreliable there.
    """
    root = _find_repo_root(repo_root)
    tag = _exact_release_tag(root)
    if tag is not None:
        return tag
    if _is_shallow_repository(root):
        raise RuntimeError(
            f"shallow clone detected in {root}: the commit count is unreliable; "
            "clone with full history (git fetch --unshallow) "
            "or check out a release tag"
        )
    moment = now if now is not None else datetime.now()
    first_day = f"{moment.year:04d}-{moment.month:02d}-01 00:00:00"
    try:
        proc = subprocess.run(
            ["git", "log", f"--since={first_day}", "--oneline"],
            cwd=root,
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError as exc:
        raise RuntimeError(f"cannot run git in {root}: {exc}") from exc
    if proc.returncode != 0:
        raise RuntimeError(f"git log failed in {root}: {proc.stderr.strip()}")
    count = len([line for line in proc.stdout.splitlines() if line.strip()])
    return f"{moment.year % 100:02d}.{moment.month}.{count}"


def write_version_file(dest: Path, version: str) -> None:
    """Write a generated file pinning ``__version__`` to ``version``."""
    target = Path(dest)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        f'# Generated by tools/versioning.py; do not edit by hand.\n__version__ = "{version}"\n',
        encoding="utf-8",
    )


def main(argv: list[str]) -> int:
    """Print the computed version for an optional repo path argument."""
    target: str | Path = argv[1] if len(argv) > 1 else "."
    print(compute_version(target))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
