"""Dynamic version computation for the box-project monorepo.

The version follows the ``year.month.commit-count`` scheme (e.g. ``26.9.4``):
two-digit year, month without leading zero, and the number of commits
reachable from HEAD since the first day of that month at 00:00:00.

The version is never stored in source files. It is computed from git
history at build/CI time and pinned into the artifact.
"""

from __future__ import annotations

import subprocess
import sys
from datetime import datetime
from pathlib import Path


def _find_repo_root(start: str | Path) -> Path:
    """Walk up from ``start`` until a directory containing ``.git`` is found."""
    current = Path(start).resolve()
    if current.is_file():
        current = current.parent
    for candidate in (current, *current.parents):
        if (candidate / ".git").exists():
            return candidate
    raise RuntimeError(
        f"no .git directory found at or above {current}; "
        "pass the monorepo root (or a path inside it) as repo_root"
    )


def compute_version(repo_root: str | Path = ".", now: datetime | None = None) -> str:
    """Compute the ``year.month.commit-count`` version from git history.

    ``repo_root`` may point anywhere inside the monorepo (the monorepo
    root itself, ``box-rpg/``, ``box-gui/``, ...); it is resolved upward
    to the directory containing ``.git`` so every package gets the same
    number. ``now`` overrides the current time (used in tests).
    """
    root = _find_repo_root(repo_root)
    moment = now if now is not None else datetime.now()
    first_day = f"{moment.year:04d}-{moment.month:02d}-01 00:00:00"
    try:
        proc = subprocess.run(
            ["git", "log", f"--since={first_day}", "--oneline"],
            cwd=root,
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError as exc:
        raise RuntimeError(f"cannot run git in {root}: {exc}") from exc
    if proc.returncode != 0:
        raise RuntimeError(f"git log failed in {root}: {proc.stderr.strip()}")
    count = len([line for line in proc.stdout.splitlines() if line.strip()])
    return f"{moment.year % 100:02d}.{moment.month}.{count}"


def write_version_file(dest: Path, version: str) -> None:
    """Write a generated file pinning ``__version__`` to ``version``."""
    target = Path(dest)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        f'# Generated by tools/versioning.py; do not edit by hand.\n__version__ = "{version}"\n',
        encoding="utf-8",
    )


def main(argv: list[str]) -> int:
    """Print the computed version for an optional repo path argument."""
    target: str | Path = argv[1] if len(argv) > 1 else "."
    print(compute_version(target))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
